/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_market_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sectors */
        get: operations["sectors_api_market_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/ribbon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ribbon */
        get: operations["ribbon_api_market_ribbon_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board/newhigh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Newhigh */
        get: operations["newhigh_api_board_newhigh_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sectors */
        get: operations["sectors_api_board_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_board_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rankings */
        get: operations["rankings_api_board_rankings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/screen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Screen */
        get: operations["screen_api_flows_screen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/investors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Investors */
        get: operations["investors_api_flows_investors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/stock/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock */
        get: operations["stock_api_flows_stock__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/intraday": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Intraday */
        get: operations["intraday_api_flows_intraday_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/etf/flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Flows */
        get: operations["flows_api_etf_flows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/etf/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Types */
        get: operations["types_api_etf_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/etf/premium": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Premium */
        get: operations["premium_api_etf_premium_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/etf/holdings/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Holding Changes */
        get: operations["holding_changes_api_etf_holdings_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telegram/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telegram Webhook */
        post: operations["telegram_webhook_telegram_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BoardEvents */
        BoardEvents: {
            /** As Of */
            as_of?: string | null;
            /** Source */
            source?: string | null;
            /** Generated At */
            generated_at?: string | null;
            /** Events */
            events?: {
                [key: string]: unknown;
            }[];
            /** Note */
            note?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** BoardFilter */
        BoardFilter: {
            /** Basis */
            basis: string;
            /** Kind */
            kind: string | null;
            /** Min Turnover Eok */
            min_turnover_eok: number | null;
            /** N Before Filter */
            n_before_filter: number;
        };
        /** BoardNewhigh */
        BoardNewhigh: {
            /** As Of */
            as_of?: string | null;
            /** Source */
            source?: string | null;
            /** Generated At */
            generated_at?: string | null;
            /** Basis */
            basis?: string | null;
            /** Prev Asof */
            prev_asof?: string | null;
            /** Thresholds */
            thresholds?: {
                [key: string]: unknown;
            };
            /** Labels */
            labels?: {
                [key: string]: string;
            };
            /** Priority */
            priority?: string[];
            /** Counts Close */
            counts_close?: {
                [key: string]: number;
            };
            /** Counts High */
            counts_high?: {
                [key: string]: number;
            };
            /** Min Mktcap Eok */
            min_mktcap_eok?: number | null;
            /** Min Turnover Eok */
            min_turnover_eok?: number | null;
            /** N Below Mktcap */
            n_below_mktcap?: number | null;
            /** N Suspect */
            n_suspect?: number | null;
            /** N Hist Not Evaluated */
            n_hist_not_evaluated?: number | null;
            /** Achieved */
            achieved?: {
                [key: string]: unknown;
            }[];
            /** Proximity */
            proximity?: {
                [key: string]: unknown;
            }[];
            /** Hist Scope */
            hist_scope?: {
                [key: string]: unknown;
            } | null;
            /** Hist Notes */
            hist_notes?: string[];
            /** Flows */
            flows?: {
                [key: string]: components["schemas"]["RowFlows"];
            };
            filter?: components["schemas"]["BoardFilter"] | null;
        } & {
            [key: string]: unknown;
        };
        /** BoardRankings */
        BoardRankings: {
            /** As Of */
            as_of?: string | null;
            /** Source */
            source?: string | null;
            /** Generated At */
            generated_at?: string | null;
            /** Prev Asof */
            prev_asof?: string | null;
            /** Taxonomy */
            taxonomy?: string | null;
            /** Universe */
            universe?: number | null;
            /** Thresholds */
            thresholds?: {
                [key: string]: unknown;
            };
            /** Sector Boards */
            sector_boards?: {
                [key: string]: unknown;
            }[];
            /** Stock Boards */
            stock_boards?: {
                [key: string]: unknown;
            }[];
            /** Cross Codes */
            cross_codes?: string[];
        } & {
            [key: string]: unknown;
        };
        /** BoardSectors */
        BoardSectors: {
            /** As Of */
            as_of?: string | null;
            /** Source */
            source?: string | null;
            /** Generated At */
            generated_at?: string | null;
            /** Taxonomy Layer1 */
            taxonomy_layer1?: string | null;
            /** Sectors */
            sectors?: {
                [key: string]: unknown;
            }[];
            /** Themes */
            themes?: {
                [key: string]: unknown;
            }[];
            /** Heatmap Theme */
            heatmap_theme?: {
                [key: string]: unknown;
            }[];
            /** Heatmap Sector */
            heatmap_sector?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** Breadth */
        Breadth: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Up */
            up: number;
            /** Flat */
            flat: number;
            /** Down */
            down: number;
            /** Unknown */
            unknown: number;
            /** Total */
            total: number;
            /** Above Ma20 N */
            above_ma20_n: number;
            /** Ma20 Base */
            ma20_base: number;
            /** Above Ma20 Pct */
            above_ma20_pct: number | null;
            /** Newhigh N */
            newhigh_n: number;
            /** Newhigh Pct */
            newhigh_pct: number | null;
            /** Limit Up */
            limit_up: number;
            /** Limit Down */
            limit_down: number;
            quality: components["schemas"]["Quality"] | null;
            /** Source */
            source: string;
            /** Notes */
            notes: string[];
        };
        /** ChangeRow */
        ChangeRow: {
            /** Fund Id */
            fund_id: string;
            /** Etf Code */
            etf_code: string | null;
            /** Fund Name */
            fund_name: string | null;
            /** Issuer */
            issuer: string | null;
            /** Is Active */
            is_active: boolean | null;
            /** Theme */
            theme: string | null;
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "NEW" | "DROP" | "IN10" | "OUT10" | "ADD" | "CUT";
            /** Kind Label */
            kind_label: string;
            /** Prev Qty */
            prev_qty: number | null;
            /** Cur Qty */
            cur_qty: number | null;
            /** Prev Wt */
            prev_wt: number | null;
            /** Cur Wt */
            cur_wt: number | null;
            /** Qty Pct Adj */
            qty_pct_adj: number | null;
            /**
             * Asof
             * Format: date
             */
            asof: string;
            /**
             * Prev Asof
             * Format: date
             */
            prev_asof: string;
            /** Gap Days */
            gap_days: number;
        };
        /**
         * Check3
         * @description 검산 ③(순자산 변화 = 순유입 + 가격효과) — 집계에 넣은 흐름의 합.
         */
        Check3: {
            /** Net Asset Chg */
            net_asset_chg: number | null;
            /** Inflow */
            inflow: number;
            /** Price Effect */
            price_effect: number;
            /** Residual */
            residual: number | null;
            /** N Checked */
            n_checked: number;
            /** N Failed */
            n_failed: number;
            /** N Unavailable */
            n_unavailable: number;
        };
        /** Chip */
        Chip: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            value: components["schemas"]["ChipValue"] | null;
            /**
             * Tier
             * @enum {string}
             */
            tier: "public" | "login";
            /** Phase Pending */
            phase_pending: string | null;
            /** Tags */
            tags: string[];
            /** Note */
            note: string | null;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
        };
        /**
         * ChipValue
         * @description 상단 띠 칩 값(수·문자 — 원천·시각·품질 필수).
         */
        ChipValue: {
            /** Value */
            value: number | string;
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
        };
        /** CsrfResponse */
        CsrfResponse: {
            /** Csrf Token */
            csrf_token: string;
        };
        /** DayFlow */
        DayFlow: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Turnover */
            turnover: number | null;
            /** Foreign */
            foreign: number | null;
            /** Inst */
            inst: number | null;
            /** Other Corp */
            other_corp: number | null;
            /** Indiv */
            indiv: number | null;
            /** Check1 */
            check1: number | null;
            /** Check2 */
            check2: number | null;
            /** Traded */
            traded: boolean;
            quality: components["schemas"]["Quality"] | null;
        };
        /** DayTotals */
        DayTotals: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** By Investor */
            by_investor: {
                [key: string]: number | null;
            };
            quality: components["schemas"]["Quality"];
        };
        /** DayValue */
        DayValue: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value: number | null;
            quality: components["schemas"]["Quality"] | null;
            /** Source */
            source: string;
        };
        /** Envelope[BoardEvents] */
        Envelope_BoardEvents_: {
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
            /** Notes */
            notes?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            data: components["schemas"]["BoardEvents"];
        };
        /** Envelope[BoardNewhigh] */
        Envelope_BoardNewhigh_: {
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
            /** Notes */
            notes?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            data: components["schemas"]["BoardNewhigh"];
        };
        /** Envelope[BoardRankings] */
        Envelope_BoardRankings_: {
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
            /** Notes */
            notes?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            data: components["schemas"]["BoardRankings"];
        };
        /** Envelope[BoardSectors] */
        Envelope_BoardSectors_: {
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
            /** Notes */
            notes?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            data: components["schemas"]["BoardSectors"];
        };
        /** Envelope[EtfFlows] */
        Envelope_EtfFlows_: {
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
            /** Notes */
            notes?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            data: components["schemas"]["EtfFlows"];
        };
        /** Envelope[EtfHoldingChanges] */
        Envelope_EtfHoldingChanges_: {
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
            /** Notes */
            notes?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            data: components["schemas"]["EtfHoldingChanges"];
        };
        /** Envelope[EtfPremium] */
        Envelope_EtfPremium_: {
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
            /** Notes */
            notes?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            data: components["schemas"]["EtfPremium"];
        };
        /** Envelope[EtfTypes] */
        Envelope_EtfTypes_: {
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
            /** Notes */
            notes?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            data: components["schemas"]["EtfTypes"];
        };
        /** Envelope[IntradayFlows] */
        Envelope_IntradayFlows_: {
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
            /** Notes */
            notes?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            data: components["schemas"]["IntradayFlows"];
        };
        /** Envelope[InvestorTotals] */
        Envelope_InvestorTotals_: {
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
            /** Notes */
            notes?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            data: components["schemas"]["InvestorTotals"];
        };
        /** Envelope[MarketSummary] */
        Envelope_MarketSummary_: {
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
            /** Notes */
            notes?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            data: components["schemas"]["MarketSummary"];
        };
        /** Envelope[Ribbon] */
        Envelope_Ribbon_: {
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
            /** Notes */
            notes?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            data: components["schemas"]["Ribbon"];
        };
        /** Envelope[ScreenResponse] */
        Envelope_ScreenResponse_: {
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
            /** Notes */
            notes?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            data: components["schemas"]["ScreenResponse"];
        };
        /** Envelope[SectorHeat] */
        Envelope_SectorHeat_: {
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
            /** Notes */
            notes?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            data: components["schemas"]["SectorHeat"];
        };
        /** Envelope[StockFlowDetail] */
        Envelope_StockFlowDetail_: {
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
            /** Notes */
            notes?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            data: components["schemas"]["StockFlowDetail"];
        };
        /**
         * ErrorBody
         * @description 오류 응답(401·403·413·415·503) — 사유 코드만, 입력값·내부 문구 없음.
         */
        ErrorBody: {
            /** Code */
            code: string;
            /**
             * Message
             * @default
             */
            message: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
        };
        /** EtfFlowRow */
        EtfFlowRow: {
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            etf_type: components["schemas"]["EtfType"];
            /** Etf Type Label */
            etf_type_label: string;
            /** Theme */
            theme: string | null;
            /** Issuer */
            issuer: string | null;
            /** Net Asset */
            net_asset: number | null;
            /** Net Inflow */
            net_inflow: number | null;
            /** Price Effect */
            price_effect: number | null;
            /** Ret Pct */
            ret_pct: number | null;
            /** Turnover */
            turnover: number | null;
            /** Indiv */
            indiv: number | null;
            /** Foreign */
            foreign: number | null;
            /** Inst */
            inst: number | null;
            /** Days */
            days: number;
            /** N Invalid */
            n_invalid: number;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "new" | "split_adjusted" | "invalid";
            quality: components["schemas"]["Quality"];
        };
        /** EtfFlows */
        EtfFlows: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "in" | "out" | "value" | "indiv" | "foreign" | "inst";
            etf_type: components["schemas"]["EtfType"] | null;
            /** Period */
            period: number;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** N Total */
            n_total: number;
            /** Rows */
            rows: components["schemas"]["EtfFlowRow"][];
            /** New Listings */
            new_listings: components["schemas"]["NewListing"][];
        };
        /** EtfHoldingChanges */
        EtfHoldingChanges: {
            /**
             * Run Date
             * Format: date
             */
            run_date: string;
            /** Rows */
            rows: components["schemas"]["ChangeRow"][];
        };
        /** EtfPremium */
        EtfPremium: {
            /**
             * Basis
             * @enum {string}
             */
            basis: "nav" | "inav";
            /** N Checked */
            n_checked: number;
            /** Rows */
            rows: components["schemas"]["PremiumRow"][];
        };
        /**
         * EtfType
         * @description ETF 유형(docs/metrics.md §8 정본 — 규칙은 `kbj.engines.etf.types.etf_type`).
         *
         *     값은 DB `prv_etf.meta.etf_type` 에 그대로 들어간다. 화면 이름은 `label`.
         * @enum {string}
         */
        EtfType: "kr_index" | "kr_theme" | "overseas" | "leveraged_inverse" | "bond_cash" | "commodity" | "other";
        /** EtfTypes */
        EtfTypes: {
            /** Period */
            period: number;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Rows */
            rows: components["schemas"]["TypeRollup"][];
            check3: components["schemas"]["Check3"];
        };
        /** Excluded */
        Excluded: {
            /** Flagged */
            flagged: number;
            /** Invalid */
            invalid: number;
            /** Below Min */
            below_min: number;
            /** Status Unknown */
            status_unknown: number;
        };
        /** Health */
        Health: {
            /** Ok */
            ok: boolean;
            /** Commit */
            commit: string | null;
        };
        /** IndexTile */
        IndexTile: {
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /** Value */
            value: number | null;
            /** Chg Pct */
            chg_pct: number | null;
            /** Spark */
            spark: number[];
            /** Live */
            live: boolean;
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
        };
        /** IntradayFlows */
        IntradayFlows: {
            /**
             * Slot
             * Format: date-time
             */
            slot: string;
            /** Top Foreign */
            top_foreign: components["schemas"]["IntradayRow"][];
            /** Top Inst */
            top_inst: components["schemas"]["IntradayRow"][];
            /** Turnover Rank */
            turnover_rank: components["schemas"]["RankItem"][];
        };
        /** IntradayRow */
        IntradayRow: {
            /** Rank */
            rank: number | null;
            /** Code */
            code: string;
            /** Value */
            value: number | null;
            /** Qty */
            qty: number | null;
        };
        /** InvestorTotals */
        InvestorTotals: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** By Investor */
            by_investor: {
                [key: string]: number | null;
            };
            /** Inst7 */
            inst7: {
                [key: string]: number;
            } | null;
            /** Check1 Residual */
            check1_residual: number | null;
            /** Check2 Residual */
            check2_residual: number | null;
            /** By Market */
            by_market: {
                [key: string]: {
                    [key: string]: number | null;
                };
            };
            quality: components["schemas"]["Quality"];
            /** Source */
            source: string;
            /** Notes */
            notes: string[];
            /** Recent */
            recent: components["schemas"]["DayTotals"][];
        };
        /**
         * LoginBody
         * @description POST /api/auth/login 본문. 값은 검증 오류 문구에 싣지 않는다(app 의 422 처리기).
         */
        LoginBody: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MarketSummary */
        MarketSummary: {
            /** Date */
            date: string | null;
            /** Indices */
            indices: components["schemas"]["IndexTile"][];
            turnover: components["schemas"]["TurnoverPanel"] | null;
            breadth: components["schemas"]["Breadth"] | null;
            investors: components["schemas"]["InvestorTotals"] | null;
        };
        /** MeResponse */
        MeResponse: {
            /** User */
            user: string;
            /** Csrf Token */
            csrf_token: string;
        };
        /** NewListing */
        NewListing: {
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /**
             * Listed On
             * Format: date
             */
            listed_on: string;
            /** Net Asset */
            net_asset: number | null;
        };
        /**
         * NoDataBody
         * @description 데이터가 아직 없을 때(404) — 화면은 '아직 없음 — <작업> <예정 시각>' 으로 그린다(§6.7).
         */
        NoDataBody: {
            /**
             * Code
             * @default no_data
             * @constant
             */
            code: "no_data";
            /** Message */
            message: string;
        };
        /** PremiumRow */
        PremiumRow: {
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /** Price */
            price: number;
            /** Nav */
            nav: number;
            /** Premium Pct */
            premium_pct: number;
            /** Threshold */
            threshold: number;
            /** Warn */
            warn: boolean;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
            /** Source */
            source: string;
        };
        /**
         * Quality
         * @description 값의 품질. 문자열 값이 그대로 DB `quality` 열과 API 응답에 들어간다.
         * @enum {string}
         */
        Quality: "ok" | "stale" | "estimated" | "invalid";
        /** RankItem */
        RankItem: {
            /** Market */
            market: string;
            /** Rank */
            rank: number;
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /** Turnover */
            turnover: number | null;
            /** Chg Pct */
            chg_pct: number | null;
        };
        /** Ribbon */
        Ribbon: {
            /** Chips */
            chips: components["schemas"]["Chip"][];
        };
        /**
         * RowFlows
         * @description 신고가 행에 붙이는 그날 원장 순매수(원) — 값이 없으면 None.
         */
        RowFlows: {
            /** Foreign */
            foreign: number | null;
            /** Inst */
            inst: number | null;
            /** Quality */
            quality: string | null;
        };
        /** ScreenResponse */
        ScreenResponse: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "value" | "foreign" | "inst" | "both" | "streak" | "spike";
            /**
             * Market
             * @enum {string}
             */
            market: "all" | "KOSPI" | "KOSDAQ";
            /** Period */
            period: number;
            /**
             * Share Class
             * @enum {string}
             */
            share_class: "common" | "pref";
            /** Min Avg Turnover */
            min_avg_turnover: number;
            /** Date */
            date: string | null;
            /** N Total */
            n_total: number;
            n_excluded: components["schemas"]["Excluded"];
            /** Rows */
            rows: components["schemas"]["ScreenRow"][];
        };
        /** ScreenRow */
        ScreenRow: {
            /** Rank */
            rank: number;
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /** Market */
            market: string | null;
            /** Sector */
            sector: string | null;
            /** Kind */
            kind: string | null;
            /** Chg Pct */
            chg_pct: number | null;
            /** Turnover Sum */
            turnover_sum: number | null;
            /** Turnover Avg */
            turnover_avg: number | null;
            /** Turnover Rate Pct */
            turnover_rate_pct: number | null;
            /** Foreign */
            foreign: number | null;
            /** Inst */
            inst: number | null;
            /** Other Corp */
            other_corp: number | null;
            /** Indiv */
            indiv: number | null;
            /** Streak Foreign */
            streak_foreign: number;
            /** Streak Inst */
            streak_inst: number;
            /** Spike Mult */
            spike_mult: number | null;
            /** Newhigh Label */
            newhigh_label: string | null;
            /** Flags */
            flags: string[] | null;
            quality: components["schemas"]["Quality"];
            /** Source */
            source: string;
        };
        /** SectorCell */
        SectorCell: {
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /** Market */
            market: string | null;
            /** Chg Pct */
            chg_pct: number | null;
            /** Turnover */
            turnover: number | null;
            quality: components["schemas"]["Quality"];
            /** Source */
            source: string;
            /** As Of */
            as_of: string | null;
            /** Note */
            note: string | null;
        };
        /** SectorHeat */
        SectorHeat: {
            /** Period */
            period: number;
            /** Cells */
            cells: components["schemas"]["SectorCell"][];
        };
        /**
         * SourcedInt
         * @description 원천이 붙은 원 단위 정수.
         */
        SourcedInt: {
            /** Value */
            value: number;
            /** Source */
            source: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            quality: components["schemas"]["Quality"];
        };
        /** StockFlowDetail */
        StockFlowDetail: {
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /** Days */
            days: components["schemas"]["DayFlow"][];
            /** Cumulative */
            cumulative: {
                [key: string]: number | null;
            };
            /** Checks */
            checks: {
                [key: string]: number;
            };
        };
        /** TurnoverPanel */
        TurnoverPanel: {
            today: components["schemas"]["SourcedInt"] | null;
            /** Basis */
            basis: ("close" | "intraday_index") | null;
            /** Avg20 */
            avg20: number | null;
            /** Ratio */
            ratio: number | null;
            /** N Prior */
            n_prior: number;
            /** Series */
            series: components["schemas"]["DayValue"][];
            /** Tags */
            tags: string[];
        };
        /** TypeRollup */
        TypeRollup: {
            etf_type: components["schemas"]["EtfType"];
            /** Label */
            label: string;
            /** Net Inflow */
            net_inflow: number;
            /** Price Effect */
            price_effect: number;
            /** N Etfs */
            n_etfs: number;
            /** N New */
            n_new: number;
            /** N Invalid */
            n_invalid: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    summary_api_market_summary_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MarketSummary_"];
                };
            };
            /** @description 세션 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 아직 없음(작업·예정 시각) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoDataBody"];
                };
            };
            /** @description 쿼리 검증 실패(입력값은 싣지 않는다) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 저장소·Redis 장애 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    sectors_api_market_sectors_get: {
        parameters: {
            query?: {
                period?: 1 | 5 | 20;
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SectorHeat_"];
                };
            };
            /** @description 세션 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 아직 없음(작업·예정 시각) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoDataBody"];
                };
            };
            /** @description 쿼리 검증 실패(입력값은 싣지 않는다) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 저장소·Redis 장애 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    ribbon_api_market_ribbon_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Ribbon_"];
                };
            };
            /** @description 세션 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 아직 없음(작업·예정 시각) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoDataBody"];
                };
            };
            /** @description 쿼리 검증 실패(입력값은 싣지 않는다) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 저장소·Redis 장애 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    newhigh_api_board_newhigh_get: {
        parameters: {
            query?: {
                date?: string | null;
                basis?: "close" | "high";
                kind?: ("hist" | "w52" | "d120") | null;
                min_turnover_eok?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_BoardNewhigh_"];
                };
            };
            /** @description 세션 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 아직 없음(작업·예정 시각) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoDataBody"];
                };
            };
            /** @description 쿼리 검증 실패(입력값은 싣지 않는다) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 저장소·Redis 장애 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    sectors_api_board_sectors_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_BoardSectors_"];
                };
            };
            /** @description 세션 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 아직 없음(작업·예정 시각) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoDataBody"];
                };
            };
            /** @description 쿼리 검증 실패(입력값은 싣지 않는다) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 저장소·Redis 장애 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    events_api_board_events_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_BoardEvents_"];
                };
            };
            /** @description 세션 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 아직 없음(작업·예정 시각) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoDataBody"];
                };
            };
            /** @description 쿼리 검증 실패(입력값은 싣지 않는다) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 저장소·Redis 장애 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    rankings_api_board_rankings_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_BoardRankings_"];
                };
            };
            /** @description 세션 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 아직 없음(작업·예정 시각) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoDataBody"];
                };
            };
            /** @description 쿼리 검증 실패(입력값은 싣지 않는다) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 저장소·Redis 장애 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    screen_api_flows_screen_get: {
        parameters: {
            query: {
                mode: "value" | "foreign" | "inst" | "both" | "streak" | "spike";
                market?: "all" | "KOSPI" | "KOSDAQ";
                period?: 1 | 5 | 20;
                min_avg_turnover?: number | null;
                include_flagged?: boolean;
                share_class?: "common" | "pref";
                limit?: number;
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScreenResponse_"];
                };
            };
            /** @description 세션 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 아직 없음(작업·예정 시각) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoDataBody"];
                };
            };
            /** @description 쿼리 검증 실패(입력값은 싣지 않는다) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 저장소·Redis 장애 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    investors_api_flows_investors_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_InvestorTotals_"];
                };
            };
            /** @description 세션 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 아직 없음(작업·예정 시각) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoDataBody"];
                };
            };
            /** @description 쿼리 검증 실패(입력값은 싣지 않는다) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 저장소·Redis 장애 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    stock_api_flows_stock__code__get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StockFlowDetail_"];
                };
            };
            /** @description 세션 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 아직 없음(작업·예정 시각) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoDataBody"];
                };
            };
            /** @description 쿼리 검증 실패(입력값은 싣지 않는다) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 저장소·Redis 장애 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    intraday_api_flows_intraday_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_IntradayFlows_"];
                };
            };
            /** @description 세션 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 아직 없음(작업·예정 시각) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoDataBody"];
                };
            };
            /** @description 쿼리 검증 실패(입력값은 싣지 않는다) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 저장소·Redis 장애 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    flows_api_etf_flows_get: {
        parameters: {
            query?: {
                mode?: "in" | "out" | "value" | "indiv" | "foreign" | "inst";
                type?: components["schemas"]["EtfType"] | null;
                period?: 1 | 5 | 20;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_EtfFlows_"];
                };
            };
            /** @description 세션 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 아직 없음(작업·예정 시각) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoDataBody"];
                };
            };
            /** @description 쿼리 검증 실패(입력값은 싣지 않는다) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 저장소·Redis 장애 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    types_api_etf_types_get: {
        parameters: {
            query?: {
                period?: 1 | 5 | 20;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_EtfTypes_"];
                };
            };
            /** @description 세션 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 아직 없음(작업·예정 시각) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoDataBody"];
                };
            };
            /** @description 쿼리 검증 실패(입력값은 싣지 않는다) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 저장소·Redis 장애 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    premium_api_etf_premium_get: {
        parameters: {
            query?: {
                basis?: "nav" | "inav";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_EtfPremium_"];
                };
            };
            /** @description 세션 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 아직 없음(작업·예정 시각) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoDataBody"];
                };
            };
            /** @description 쿼리 검증 실패(입력값은 싣지 않는다) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 저장소·Redis 장애 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    holding_changes_api_etf_holdings_changes_get: {
        parameters: {
            query?: {
                date?: string | null;
                kind?: string | null;
                issuer?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_EtfHoldingChanges_"];
                };
            };
            /** @description 세션 없음·만료 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 아직 없음(작업·예정 시각) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoDataBody"];
                };
            };
            /** @description 쿼리 검증 실패(입력값은 싣지 않는다) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 저장소·Redis 장애 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    telegram_webhook_telegram_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
